package(default_visibility = ["//compiler:__subpackages__"])

py_library(
    name = "linker",
    srcs = ["linker.py"],
)

py_library(
    name = "page",
    srcs = ["page.py"],
    deps = [":linker"],
)
